export type Post = {
  slug: string;
  title: string;
  description: string;
  date: string;
  readMinutes: number;
  keyword: string;
  body: { type: 'p' | 'h2' | 'h3' | 'li' | 'cta'; text: string }[];
};

export const POSTS: Post[] = [
  {
    slug: 'how-to-speak-fluent-english',
    title: 'How to Speak Fluent English: 7 Habits That Actually Work',
    description:
      'Forget grammar books. These seven habits — backed by how fluency actually develops — will move you from hesitant to fluent in a few months.',
    date: '2026-04-19',
    readMinutes: 9,
    keyword: 'how to speak fluent english',
    body: [
      { type: 'p', text: 'Fluency is not a vocabulary problem. Most learners who struggle to speak English already know enough words. What they lack is the ability to produce those words under the light pressure of real conversation. The seven habits below target exactly that — the gap between knowing and speaking.' },
      { type: 'h2', text: '1. Speak every single day, even for five minutes' },
      { type: 'p', text: 'The single strongest predictor of fluency improvement is daily speaking time. Not weekly. Daily. Five minutes of real speaking beats an hour of passive reading. Set a floor you can hit on your worst day and never miss it.' },
      { type: 'h2', text: '2. Record yourself and listen back' },
      { type: 'p', text: 'Most learners never hear themselves. Record a 60-second answer to any question and play it back the next day. The gap between how you sound in your head and how you actually sound is where most of the improvement hides.' },
      { type: 'h2', text: '3. Stop translating from your first language' },
      { type: 'p', text: 'If you think the sentence in Hindi and translate word-by-word into English, you will always sound a beat slower than you are. Practice forming short thoughts directly in English — one clause at a time, not one word at a time.' },
      { type: 'h2', text: '4. Shadow one speaker you like' },
      { type: 'p', text: 'Pick a podcast or YouTube speaker whose English you admire. Repeat their sentences aloud, matching their rhythm, stress, and pause pattern. Fifteen minutes a day of shadowing changes the music of your English faster than any grammar drill.' },
      { type: 'h2', text: '5. Talk out loud when you are alone' },
      { type: 'p', text: 'Narrate what you are doing. Describe the room. Summarize the article you just read, out loud. You remove the social anxiety that stops most learners, and you quadruple your speaking volume for free.' },
      { type: 'h2', text: '6. Get corrected with reasons, not red lines' },
      { type: 'p', text: 'A correction without a reason is a memorized fix. A correction with a reason is a pattern you own. Work with tutors, apps, or study partners who tell you why — not just what.' },
      { type: 'h2', text: '7. Build a topic vocabulary, not a general one' },
      { type: 'p', text: 'Generic vocabulary lists are nearly useless. Pick three topics you actually talk about — work, family, a hobby — and build thirty precise phrases per topic. Deep beats wide every time.' },
      { type: 'h2', text: 'How Talkivo helps you stick to these habits' },
      { type: 'p', text: 'Talkivo is an AI English tutor that listens to your full thought, corrects with reason, and remembers the mistakes you keep making. It is designed for daily 15-minute sessions — the cadence that actually produces fluency. Free Talk mode covers habits 1, 2, and 5. Grammar Fix covers habit 6. Pronunciation mode covers habit 4.' },
      { type: 'cta', text: 'Start your first free Talkivo session →' },
    ],
  },
  {
    slug: 'ielts-speaking-band-8-guide',
    title: 'IELTS Speaking Band 8: The Full Preparation Guide',
    description:
      'What Band 8 actually sounds like, the four criteria examiners score on, and a 30-day practice plan to move from Band 6.5 to Band 8.',
    date: '2026-04-19',
    readMinutes: 14,
    keyword: 'ielts speaking band 8',
    body: [
      { type: 'p', text: 'Band 8 in IELTS Speaking is not about perfect grammar or a fake accent. It is about four specific things, scored by the examiner across three parts of the test. This guide breaks down exactly what they are and gives you a 30-day plan to move from Band 6.5 to Band 8.' },
      { type: 'h2', text: 'What IELTS Speaking actually scores' },
      { type: 'p', text: 'Four criteria, equally weighted:' },
      { type: 'li', text: 'Fluency and Coherence — can you speak at length without long pauses or self-corrections, with ideas that follow logically?' },
      { type: 'li', text: 'Lexical Resource — do you use a wide range of vocabulary with precision, including less common words and collocations?' },
      { type: 'li', text: 'Grammatical Range and Accuracy — do you use a mix of simple and complex structures mostly correctly?' },
      { type: 'li', text: 'Pronunciation — are you clear, with natural stress and intonation, easy to understand at all times?' },
      { type: 'h2', text: 'The three parts, and what Band 8 sounds like in each' },
      { type: 'h3', text: 'Part 1 — Interview (4-5 min)' },
      { type: 'p', text: 'Short personal questions. Home, family, work, hobbies. Band 8 answers are two to three sentences long — not one, not five. You give a direct answer, a small justification, and a concrete example. You sound conversational, not rehearsed.' },
      { type: 'h3', text: 'Part 2 — Long Turn (3-4 min)' },
      { type: 'p', text: 'A cue card with four bullet points. You get one minute to prepare, then speak for one to two minutes. Band 8 answers cover all four bullets, use at least two complex structures, and include two or three less common words used correctly. You do not run out of things to say.' },
      { type: 'h3', text: 'Part 3 — Discussion (4-5 min)' },
      { type: 'p', text: 'Abstract follow-up questions. Society, trends, future. Band 8 answers compare, hypothesize, and concede — "it depends on", "one could argue that", "in the long run". You go beyond opinion into analysis.' },
      { type: 'h2', text: 'The 30-day plan' },
      { type: 'h3', text: 'Week 1 — Fluency floor' },
      { type: 'p', text: 'Goal: never pause for longer than 2 seconds mid-sentence. Daily drill: 15 minutes of Free Talk on any topic. Record and listen back. Count your self-corrections. Aim to reduce them by half by end of week.' },
      { type: 'h3', text: 'Week 2 — Lexical upgrade' },
      { type: 'p', text: 'Goal: retire 10 overused words (good, bad, big, thing, very, nice, people, problem, important, do). Build a replacement list with more precise alternatives. Force yourself to use two less common words in every answer.' },
      { type: 'h3', text: 'Week 3 — Grammar range' },
      { type: 'p', text: 'Goal: use at least three complex structures naturally — conditionals, relative clauses, passive where appropriate. Practice 10 cue cards a day, forcing at least two complex sentences per answer.' },
      { type: 'h3', text: 'Week 4 — Full mock tests' },
      { type: 'p', text: 'Goal: simulate the real test. One full 11-14 minute mock per day, recorded. Review against all four criteria. Close the weakest gap each day.' },
      { type: 'h2', text: 'How Talkivo fits into the plan' },
      { type: 'p', text: 'Talkivo Role Play mode runs the full IELTS Speaking test — Part 1, Part 2 cue cards, Part 3 discussion — and scores you against the official rubric. Use Free Talk for fluency drills, Grammar Fix for written sentence upgrades you then speak aloud, and Pronunciation for the clarity work that lifts Band 7 to Band 8.' },
      { type: 'cta', text: 'Start IELTS practice with Talkivo — free →' },
    ],
  },
  {
    slug: 'ai-english-tutor-how-it-works',
    title: 'How AI English Tutors Work — And Why They Beat Flashcards',
    description:
      'The difference between memorization apps and real AI tutors, how speech recognition and feedback loops actually work, and what to look for when choosing one.',
    date: '2026-04-19',
    readMinutes: 8,
    keyword: 'ai english tutor',
    body: [
      { type: 'p', text: 'The term "AI English tutor" covers everything from flashcard apps with a chatbot bolted on, to genuine conversational AI that listens, corrects, and adapts. The difference matters. Here is what actually makes an AI tutor work.' },
      { type: 'h2', text: 'What an AI English tutor actually does' },
      { type: 'p', text: 'A real AI English tutor does four things in sequence: it listens to your speech, transcribes it accurately, understands the meaning and errors, and responds naturally — both with a conversational reply and with structured feedback on what you said.' },
      { type: 'h2', text: 'Why AI beats flashcards for speaking' },
      { type: 'p', text: 'Flashcards test recall. Speaking is production under pressure. An AI tutor gives you the one thing flashcards cannot — unlimited, judgment-free speaking time with instant feedback. That is where fluency actually builds.' },
      { type: 'h2', text: 'The three components of a good AI tutor' },
      { type: 'h3', text: '1. Speech recognition tuned for non-native speakers' },
      { type: 'p', text: 'Generic speech-to-text is trained on native speakers and misrecognizes accented English. A good AI tutor uses models adapted for Indian, South Asian, and other non-native English accents — so the corrections target what you actually said, not what the system thought you said.' },
      { type: 'h3', text: '2. Error analysis that explains, not just flags' },
      { type: 'p', text: 'A red line is not teaching. A good AI tutor points to the error, explains the rule, and shows the pattern — so the next time you speak, you catch it yourself.' },
      { type: 'h3', text: '3. Memory that persists across sessions' },
      { type: 'p', text: 'Fluency work is weeks, not hours. A good AI tutor remembers your recurring mistakes, the topics you practice, and the level you are at — and quietly adapts as you improve.' },
      { type: 'h2', text: 'What to avoid' },
      { type: 'p', text: 'Apps that only give multiple-choice grammar drills, or chatbots that respond with canned replies, are not AI tutors — they are worksheets with a friendly skin. Look for tools that let you speak freely, on any topic, and give feedback with reasons.' },
      { type: 'h2', text: 'How Talkivo approaches it' },
      { type: 'p', text: 'Talkivo is built around the idea that fluency comes from talking, not from memorizing. Its AI tutor listens without interrupting, corrects with reasons, and remembers the patterns you keep repeating. Five modes — Free Talk, Role Play, Debate, Grammar Fix, Pronunciation — cover the full range of speaking practice.' },
      { type: 'cta', text: 'Try Talkivo free — no credit card →' },
    ],
  },
  {
    slug: 'english-speaking-practice-app',
    title: 'English Speaking Practice App — 12 Tested Picks for 2026',
    description:
      'Compared 12 English speaking apps hands-on. Which are worth your time, which are marketing fluff, and what to look for before you subscribe.',
    date: '2026-04-18',
    readMinutes: 11,
    keyword: 'english speaking practice app',
    body: [
      { type: 'p', text: 'There are more English speaking apps than any learner needs. Most overlap. A few are genuinely useful. Below is a hands-on comparison of 12 — what each does well, where each falls short, and how to pick the one that fits your level and goal.' },
      { type: 'h2', text: 'What a good speaking app must do' },
      { type: 'li', text: 'Let you speak freely — not just tap buttons or read prompts.' },
      { type: 'li', text: 'Give feedback with reasons, not just red lines.' },
      { type: 'li', text: 'Remember your recurring mistakes across sessions.' },
      { type: 'li', text: 'Handle non-native accents without constant misrecognition.' },
      { type: 'li', text: 'Work in short sessions — 10-15 minutes is the realistic daily slot.' },
      { type: 'h2', text: 'The 12 apps, ranked by daily-driver usefulness' },
      { type: 'h3', text: '1. Talkivo' },
      { type: 'p', text: 'Built for unscripted speaking practice. Listens to the full thought, corrects with reason, remembers your patterns. Five modes cover conversation, role play, debate, grammar, pronunciation. Strongest for working professionals and IELTS prep.' },
      { type: 'h3', text: '2. Cambly' },
      { type: 'p', text: 'Live human tutors on demand. Great for accountability, expensive for daily practice. Quality varies by tutor.' },
      { type: 'h3', text: '3. Duolingo' },
      { type: 'p', text: 'Excellent for vocabulary and grammar basics. Weak for speaking fluency — the speaking exercises are mostly sentence repetition, not conversation.' },
      { type: 'h3', text: '4. Preply' },
      { type: 'p', text: 'Hire-your-own-tutor marketplace. Best if you find a great tutor and stick with them. Not ideal for short daily practice because scheduling friction kills consistency.' },
      { type: 'h3', text: '5. italki' },
      { type: 'p', text: 'Similar to Preply. Broader tutor pool including community (non-professional) tutors at lower prices. Same scheduling friction.' },
      { type: 'h3', text: '6. ELSA Speak' },
      { type: 'p', text: 'Strong pronunciation feedback. Narrow scope — it only does pronunciation, not conversation. Good companion app, not a standalone solution.' },
      { type: 'h3', text: '7. HelloTalk' },
      { type: 'p', text: 'Chat with native speakers globally. Free, social-media-style. Quality unpredictable. Works if you enjoy the social angle; not structured learning.' },
      { type: 'h3', text: '8. Tandem' },
      { type: 'p', text: 'Similar to HelloTalk. Language exchange format — you help them with your language, they help you with English.' },
      { type: 'h3', text: '9. Babbel' },
      { type: 'p', text: 'Structured courses with speaking exercises. Good for absolute beginners. Plateaus fast for intermediate+ learners.' },
      { type: 'h3', text: '10. Pimsleur' },
      { type: 'p', text: 'Audio-first, 30-minute lessons. Great for commute practice. Outdated interface, slow pace for modern learners.' },
      { type: 'h3', text: '11. Busuu' },
      { type: 'p', text: 'Community-corrected exercises — you submit a spoken or written answer, native speakers correct it. Corrections slow to arrive; hit-or-miss quality.' },
      { type: 'h3', text: '12. Speechify' },
      { type: 'p', text: 'Text-to-speech for accent modeling. Useful as a shadowing tool, not a conversation tool.' },
      { type: 'h2', text: 'How to actually pick one' },
      { type: 'p', text: 'Pick the tool that matches your daily time budget and your biggest gap. If you have 15 minutes a day and your gap is fluency under pressure, pick a conversation-first AI tutor. If your gap is specific pronunciation sounds, layer in ELSA. If your schedule allows weekly 45-minute lessons, a Preply tutor you trust is hard to beat.' },
      { type: 'h2', text: 'Why Talkivo shows up first' },
      { type: 'p', text: 'Disclosure — this is the Talkivo blog. That said, the ranking reflects what most working professionals actually need: daily unscripted speaking with patient, reasoned feedback. Most apps on this list were built for one narrower job; Talkivo was built for the whole workflow.' },
      { type: 'cta', text: 'Try Talkivo free — no credit card →' },
    ],
  },
  {
    slug: 'job-interview-english-practice',
    title: 'Job Interview English: 25 Questions with Scripts to Practice',
    description:
      'The 25 English interview questions that actually come up — with strong answer scripts, filler words to avoid, and a 7-day practice plan before your interview.',
    date: '2026-04-17',
    readMinutes: 13,
    keyword: 'job interview english practice',
    body: [
      { type: 'p', text: 'Most interview prep advice is about content. This guide is about language — the specific English phrases, structures, and fillers that move you from hesitant to confident in a job interview. Plus 25 of the most common questions with strong answer scripts.' },
      { type: 'h2', text: 'The four language failures that tank interviews' },
      { type: 'li', text: 'Too many filler words — "uh", "basically", "like", "so", "you know".' },
      { type: 'li', text: 'Flat, memorized answers that sound rehearsed.' },
      { type: 'li', text: 'Long, run-on sentences where the point gets lost.' },
      { type: 'li', text: 'Over-use of "I think" — weakens every statement.' },
      { type: 'h2', text: 'The STAR structure in plain English' },
      { type: 'p', text: 'For behavioral questions, use STAR: Situation, Task, Action, Result. In English, this maps to four short sentences — one for each. Avoid long build-ups. The recruiter wants the result fast.' },
      { type: 'h2', text: '25 common interview questions and answer structures' },
      { type: 'h3', text: 'Opening questions' },
      { type: 'li', text: '1. Tell me about yourself. → 90-second narrative: now, then, why next.' },
      { type: 'li', text: '2. Why do you want to work here? → Specific product or value, plus personal alignment.' },
      { type: 'li', text: '3. Why are you leaving your current role? → Forward-looking, never negative.' },
      { type: 'li', text: '4. What interests you about this role? → Two concrete responsibilities that excite you.' },
      { type: 'li', text: '5. What do you know about our company? → One product fact, one news item, one question.' },
      { type: 'h3', text: 'Behavioral questions' },
      { type: 'li', text: '6. Tell me about a time you failed. → Real failure, lesson, specific change afterwards.' },
      { type: 'li', text: '7. Tell me about a conflict with a colleague. → Empathetic, solution-oriented.' },
      { type: 'li', text: '8. Describe your proudest achievement. → Measurable outcome, your specific contribution.' },
      { type: 'li', text: '9. Tell me about a time you led a project. → STAR format, clear result.' },
      { type: 'li', text: '10. How do you handle pressure? → Specific example, not platitudes.' },
      { type: 'h3', text: 'Skill and fit questions' },
      { type: 'li', text: '11. What are your strengths? → Three, each with a concrete example.' },
      { type: 'li', text: '12. What are your weaknesses? → Real weakness, active effort to improve.' },
      { type: 'li', text: '13. Where do you see yourself in five years? → Role trajectory that makes sense for this company.' },
      { type: 'li', text: '14. Why should we hire you? → Match their top requirements to your experience.' },
      { type: 'li', text: '15. How do you prioritize work? → Concrete framework, real example.' },
      { type: 'h3', text: 'Tough questions' },
      { type: 'li', text: '16. What is your expected salary? → Research-backed range, not a single number.' },
      { type: 'li', text: '17. Why the gap on your resume? → Direct, short, forward-looking.' },
      { type: 'li', text: '18. What would your last manager say about you? → Specific, with one tough truth.' },
      { type: 'li', text: '19. How do you handle disagreement with leadership? → Respectful, data-driven.' },
      { type: 'li', text: '20. What do you do outside of work? → One real interest, not a list.' },
      { type: 'h3', text: 'Closing questions' },
      { type: 'li', text: '21. Do you have any questions for us? → Three, on culture, growth, and the actual work.' },
      { type: 'li', text: '22. When can you start? → Direct number of days/weeks.' },
      { type: 'li', text: '23. Are you interviewing elsewhere? → Honest but not specific.' },
      { type: 'li', text: '24. What are you looking for in a role? → Three concrete things.' },
      { type: 'li', text: '25. Is there anything else we should know? → One strong reinforcing point.' },
      { type: 'h2', text: 'The 7-day practice plan' },
      { type: 'p', text: 'Day 1-2: Write answers to the 10 most likely questions in your own words. Day 3-4: Record yourself answering them out loud, no notes. Day 5-6: Practice with a partner or AI tutor. Day 7: Rest. Avoid cramming the night before — it degrades fluency.' },
      { type: 'h2', text: 'How Talkivo helps you prepare' },
      { type: 'p', text: 'Talkivo Role Play mode includes job-interview scenarios across common roles — product, engineering, consulting, sales, customer support. The AI plays the recruiter, stays in character, and gives feedback on clarity, filler usage, and pace at the end of each session.' },
      { type: 'cta', text: 'Practice interviews with Talkivo — free →' },
    ],
  },
  {
    slug: 'english-pronunciation-india',
    title: 'English Pronunciation: The 18 Sounds Indian Speakers Struggle With',
    description:
      'Eighteen specific English sounds that most Indian speakers avoid or replace — with mouth-position cues, minimal pairs, and a practice sequence that works.',
    date: '2026-04-16',
    readMinutes: 10,
    keyword: 'english pronunciation india',
    body: [
      { type: 'p', text: 'Pronunciation is the most common reason fluent Indian English speakers get asked to repeat themselves on international calls. The grammar is right. The vocabulary is right. A few specific sounds aren\u2019t landing. Here are the 18 that cause the most friction — and how to fix each.' },
      { type: 'h2', text: 'Why these sounds are hard' },
      { type: 'p', text: 'Most Indian languages don\u2019t have direct equivalents for these sounds, so speakers learn English by approximating them with the nearest native-language sound. The approximations are understandable in India but cause miscommunication in international contexts.' },
      { type: 'h2', text: 'The 18 sounds' },
      { type: 'h3', text: 'Consonants (12)' },
      { type: 'li', text: '1. /θ/ as in "think" — often replaced with /t/. Practice: tongue between teeth, soft airflow.' },
      { type: 'li', text: '2. /\u00F0/ as in "this" — often replaced with /d/. Same tongue position as /θ/ but voiced.' },
      { type: 'li', text: '3. /v/ as in "very" — often merged with /w/. Practice: top teeth lightly on bottom lip.' },
      { type: 'li', text: '4. /w/ as in "water" — often over-rounded. Practice: minimal lip rounding, quick release.' },
      { type: 'li', text: '5. /z/ as in "zoo" — often replaced with /s/. Voiced, vocal cords active.' },
      { type: 'li', text: '6. /\u0292/ as in "measure" — often replaced with /s/ or /z/. Soft, voiced, palate position.' },
      { type: 'li', text: '7. /f/ at sentence end — often softened. Keep airflow strong through to the end.' },
      { type: 'li', text: '8. Dark /l/ as in "full" — often replaced with light /l/. Back of tongue raised.' },
      { type: 'li', text: '9. /t/ between vowels as in "water" — Indian speakers often produce crisp /t/; American English uses a flap.' },
      { type: 'li', text: '10. /r/ post-vocalic as in "car" — non-rhotic in Indian English; rhotic in American.' },
      { type: 'li', text: '11. /\u014B/ as in "sing" — often followed by an unnecessary /g/.' },
      { type: 'li', text: '12. /p t k/ aspiration — Indian speakers often under-aspirate at the start of stressed syllables.' },
      { type: 'h3', text: 'Vowels (6)' },
      { type: 'li', text: '13. /\u00E6/ as in "cat" — often replaced with /e/ or /a/. Low, front, unrounded.' },
      { type: 'li', text: '14. /\u028C/ as in "cup" — often replaced with /a/. Mid-central, unrounded.' },
      { type: 'li', text: '15. Schwa /\u0259/ in unstressed syllables — often fully pronounced. Key to natural rhythm.' },
      { type: 'li', text: '16. /i/ vs /\u026A/ — "beat" vs "bit" — often merged.' },
      { type: 'li', text: '17. /u/ vs /\u028A/ — "pool" vs "pull" — often merged.' },
      { type: 'li', text: '18. Diphthongs /a\u028A/ as in "now" — often monophthongized.' },
      { type: 'h2', text: 'The practice sequence that works' },
      { type: 'p', text: 'Pick one sound. Do minimal-pair drills for 5 minutes (think/tink, very/wery). Then 5 minutes of sentence-level practice with that sound in every word. Then record yourself reading a paragraph that contains the sound 10+ times. Listen back. One sound per day, cycle through all 18. In three weeks you will feel the difference; in six weeks listeners will.' },
      { type: 'h2', text: 'How Talkivo Pronunciation mode helps' },
      { type: 'p', text: 'Pronunciation mode drills all 18 sounds with minimal-pair practice, sentence-level reading, and instant feedback on where your production drifted. Built for Indian and South Asian speakers specifically.' },
      { type: 'cta', text: 'Drill pronunciation with Talkivo — free →' },
    ],
  },
  {
    slug: 'english-fluency-test',
    title: 'English Fluency Test — Measure Yourself in 10 Minutes',
    description:
      'A practical self-test for English speaking fluency — four tasks, scored on five dimensions, with a level-appropriate practice plan for each result.',
    date: '2026-04-15',
    readMinutes: 7,
    keyword: 'english fluency test',
    body: [
      { type: 'p', text: 'Most online "English fluency tests" measure grammar recognition, not speaking fluency. This one measures speaking — four tasks, 10 minutes total, scored on five dimensions. You will know where you stand and what to work on next.' },
      { type: 'h2', text: 'The four tasks' },
      { type: 'h3', text: 'Task 1 — 60-second self-introduction (warm-up)' },
      { type: 'p', text: 'Speak for 60 seconds about who you are, what you do, and what you are working toward. No preparation. Record it.' },
      { type: 'h3', text: 'Task 2 — Describe a photo' },
      { type: 'p', text: 'Pick any photo on your phone. Describe it in English for 90 seconds — what you see, what is happening, what came before, what will happen next.' },
      { type: 'h3', text: 'Task 3 — Argue a side' },
      { type: 'p', text: 'Pick a topic you have an opinion on. Argue one side for 90 seconds. Then switch and argue the opposite side for 90 seconds.' },
      { type: 'h3', text: 'Task 4 — Summarize an article' },
      { type: 'p', text: 'Pick a news article you read today. Summarize it aloud in 90 seconds — key points, why it matters, your reaction.' },
      { type: 'h2', text: 'The five dimensions to score yourself on' },
      { type: 'li', text: 'Fluency — Did you pause for more than 2 seconds mid-sentence? Count the pauses. 0 = excellent, 5+ = needs work.' },
      { type: 'li', text: 'Accuracy — Grammar mistakes per minute. 0-1 = advanced, 4+ = intermediate.' },
      { type: 'li', text: 'Range — How many different grammar structures and vocabulary areas did you use? Or did you cycle the same 10 words?' },
      { type: 'li', text: 'Pronunciation — Did any word require you to repeat it for the listener (or yourself)?' },
      { type: 'li', text: 'Interaction — In Task 3, did you sound like you were arguing, or just listing points?' },
      { type: 'h2', text: 'What each level sounds like' },
      { type: 'h3', text: 'Beginner (CEFR A2-B1)' },
      { type: 'p', text: 'Short sentences. Noticeable pauses between thoughts. Limited vocabulary range. Grammar errors in most sentences. Understandable but slow.' },
      { type: 'h3', text: 'Intermediate (CEFR B1-B2)' },
      { type: 'p', text: 'Can sustain a 90-second monologue. Grammar mostly right. Vocabulary covers everyday topics. Hesitation on abstract or less familiar topics.' },
      { type: 'h3', text: 'Advanced (CEFR B2-C1)' },
      { type: 'p', text: 'Fluent across familiar and abstract topics. Complex grammar used naturally. Vocabulary includes idiom and register-appropriate choices. Occasional minor errors.' },
      { type: 'h3', text: 'Near-native (CEFR C1-C2)' },
      { type: 'p', text: 'Indistinguishable from a fluent non-native professional. Errors rare and minor. Pronunciation clear and consistent. Register shifts effortlessly.' },
      { type: 'h2', text: 'The plan after the test' },
      { type: 'p', text: 'Beginner: 20 minutes a day of Free Talk on easy topics. Intermediate: 15 minutes daily across Free Talk, Grammar Fix, and Pronunciation. Advanced: 10 minutes daily of Debate and Role Play on challenging topics.' },
      { type: 'cta', text: 'Start practicing at your level — free →' },
    ],
  },
  {
    slug: 'spoken-english-course-online',
    title: 'Spoken English Course Online — A Full 30-Day Plan',
    description:
      'A 30-day self-directed plan to move from hesitant to confident English speaking. Daily 15-minute sessions, with exactly what to practice and how to measure progress.',
    date: '2026-04-14',
    readMinutes: 10,
    keyword: 'spoken english course online',
    body: [
      { type: 'p', text: 'Most "spoken English courses" are video libraries you passively watch. This 30-day plan is different — it is 15 minutes of active speaking every day, with exactly what to practice and how to track progress. Free to follow. No course fee.' },
      { type: 'h2', text: 'The three principles' },
      { type: 'li', text: 'Daily beats intense. Fifteen minutes every day beats three hours once a week.' },
      { type: 'li', text: 'Active beats passive. Speaking out loud beats watching lessons.' },
      { type: 'li', text: 'Feedback beats volume. Corrections with reasons beat more minutes without them.' },
      { type: 'h2', text: 'Week 1 — Fluency floor' },
      { type: 'p', text: 'Goal: speak for 15 minutes daily without stopping. Topic: your life (work, family, city, weekend). Record each session. Measure pauses — aim to reduce them by half by day 7.' },
      { type: 'h2', text: 'Week 2 — Vocabulary lift' },
      { type: 'p', text: 'Goal: retire 10 overused words (good, bad, thing, do, get, nice, big, very, people, problem). Build a replacement list. Use at least two less common words per answer. Practice on new topics each day — travel, food, music, technology, books.' },
      { type: 'h2', text: 'Week 3 — Grammar range' },
      { type: 'p', text: 'Goal: add complex grammar. Use at least one conditional (If I had..., I would...) and one relative clause (The thing I like most is...) per session. Practice with Role Play scenarios — interviews, customer service, complaints.' },
      { type: 'h2', text: 'Week 4 — Pressure testing' },
      { type: 'p', text: 'Goal: speak under pressure. Debate a topic you disagree with. Role play a difficult conversation. Give a 3-minute spontaneous talk. Record and review. By day 30 you should sound 30-50% more fluent than day 1.' },
      { type: 'h2', text: 'How to measure progress objectively' },
      { type: 'li', text: 'Count pauses longer than 2 seconds in a 60-second recording. Fewer = better.' },
      { type: 'li', text: 'Count distinct vocabulary items (unique words) in a 90-second monologue. More = better.' },
      { type: 'li', text: 'Count grammar errors per minute. Fewer = better.' },
      { type: 'li', text: 'Ask someone to rate your clarity on a 1-5 scale. Higher = better.' },
      { type: 'h2', text: 'How Talkivo structures the 30 days' },
      { type: 'p', text: 'Talkivo maps the above plan to its five modes — Free Talk for weeks 1-2 fluency and vocabulary, Grammar Fix and Role Play for week 3, Debate and Pronunciation for week 4. Sessions are 10-15 minutes. The tutor remembers your patterns and builds on them each day.' },
      { type: 'cta', text: 'Start the 30-day plan with Talkivo — free →' },
    ],
  },
  {
    slug: 'think-in-english',
    title: 'How to Think in English (Stop Translating from Hindi)',
    description:
      'Why translating from your first language slows you down — and five concrete drills that train your brain to form thoughts directly in English.',
    date: '2026-04-13',
    readMinutes: 7,
    keyword: 'think in english',
    body: [
      { type: 'p', text: 'The biggest block to fluent English isn\u2019t vocabulary. It\u2019s the translation loop — you think in Hindi or Telugu, translate to English, then speak. That loop is slower than the conversation moves. This guide is about breaking the loop.' },
      { type: 'h2', text: 'Why translation kills fluency' },
      { type: 'p', text: 'Translation uses extra cognitive steps. By the time you finish translating, the conversation has moved on. You also import grammar structures from your first language, which sound unnatural in English.' },
      { type: 'h2', text: 'Five drills to think in English' },
      { type: 'h3', text: 'Drill 1 — Narrate your day silently' },
      { type: 'p', text: 'As you walk, cook, commute — describe what you are doing in your head, in English, in present continuous. "I am walking to the kitchen. I am opening the fridge." Simple, constant, builds the habit.' },
      { type: 'h3', text: 'Drill 2 — Single-word naming' },
      { type: 'p', text: 'Look around. Name every object you see, in English only. When you don\u2019t know a word, note it to look up later. Forces direct object-to-English mapping.' },
      { type: 'h3', text: 'Drill 3 — English journaling, three lines' },
      { type: 'p', text: 'Every night, write three lines in English about your day. No editing. The speed of writing trains the speed of thinking.' },
      { type: 'h3', text: 'Drill 4 — Input flood' },
      { type: 'p', text: 'Change your phone, social media, and YouTube to English. Watch one show a week in English with English subtitles, not your native language ones. Your brain stops reaching for translations when English is the default input.' },
      { type: 'h3', text: 'Drill 5 — Talk to yourself out loud' },
      { type: 'p', text: 'For 10 minutes a day, speak English out loud — to yourself, to a wall, to an AI tutor. No audience pressure. The translation loop only breaks through real production, not through reading.' },
      { type: 'h2', text: 'How long does it take?' },
      { type: 'p', text: 'Most learners report thinking in English for simple topics within 2-3 weeks of daily practice. Abstract thinking in English follows within 6-8 weeks. The translation loop doesn\u2019t disappear — it just gets shorter and less frequent.' },
      { type: 'h2', text: 'Where Talkivo fits' },
      { type: 'p', text: 'Talkivo\u2019s Free Talk mode is a translation-breaker. Because the AI responds fast, you don\u2019t have time to translate — you have to produce. Over weeks, the translation loop thins and finally falls away.' },
      { type: 'cta', text: 'Break the translation loop with Talkivo — free →' },
    ],
  },
  {
    slug: 'english-grammar-check-ai',
    title: 'AI Grammar Checker for English: What to Look For in 2026',
    description:
      'Grammarly, LanguageTool, Talkivo, ChatGPT, and more — which AI grammar checker gives you real learning, not just fixes. A practical comparison.',
    date: '2026-04-12',
    readMinutes: 8,
    keyword: 'ai grammar checker english',
    body: [
      { type: 'p', text: 'Every writer and serious learner needs an AI grammar checker. But most are built to produce clean text, not to teach you. Here is how to tell the difference, and how five popular tools compare for real language learning.' },
      { type: 'h2', text: 'Fixer vs tutor — the core distinction' },
      { type: 'p', text: 'A fixer rewrites your sentence. A tutor explains why the rewrite is better. Fixers are faster; tutors make you a better writer. For learners, tutors beat fixers every time.' },
      { type: 'h2', text: 'Five tools compared' },
      { type: 'h3', text: 'Grammarly' },
      { type: 'p', text: 'Excellent fixer. Ubiquitous. Explains some changes but keeps explanations shallow. Great for polishing; weak for learning.' },
      { type: 'h3', text: 'LanguageTool' },
      { type: 'p', text: 'Open-source alternative to Grammarly. Rule-based, less AI-driven. Strong multilingual support. Similar fixer-first bias.' },
      { type: 'h3', text: 'ChatGPT / Claude (general LLMs)' },
      { type: 'p', text: 'Can explain grammar in detail when you prompt them to. Best with a careful prompt. Risk: over-rewriting, changing your voice. Not purpose-built for learning.' },
      { type: 'h3', text: 'Talkivo Grammar Fix' },
      { type: 'p', text: 'Purpose-built tutor. Every change comes with the reason, and it tracks the patterns you repeat so it can surface a focus plan over weeks. Built around learning, not just producing.' },
      { type: 'h3', text: 'ProWritingAid' },
      { type: 'p', text: 'Strong on style and readability analysis beyond pure grammar. Useful for long-form writers. Heavier interface.' },
      { type: 'h2', text: 'What to look for if you want to learn, not just fix' },
      { type: 'li', text: 'Does every correction come with a reason you can remember?' },
      { type: 'li', text: 'Does the tool track recurring mistakes across sessions?' },
      { type: 'li', text: 'Does it adapt to your voice or flatten it?' },
      { type: 'li', text: 'Does it handle conversational and business English, not just academic?' },
      { type: 'h2', text: 'Use both, for different jobs' },
      { type: 'p', text: 'Use Grammarly when you need to send an email fast. Use Talkivo when you want to get better at writing so you need Grammarly less often. They solve different problems.' },
      { type: 'cta', text: 'Try Talkivo Grammar Fix — free →' },
    ],
  },
];

export function getPost(slug: string) {
  return POSTS.find((p) => p.slug === slug);
}
